---
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh:
    forward_agent: true

platforms:
- name: centos-5-8-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-6-5-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: debian-6-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: debian-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: ubuntu-10-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]
